// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetMockEvents() {
  return window['go']['main']['App']['GetMockEvents']();
}

export function SendToScoreboard(arg1) {
  return window['go']['main']['App']['SendToScoreboard'](arg1);
}

export function TriggerEDM() {
  return window['go']['main']['App']['TriggerEDM']();
}

export function TriggerWind() {
  return window['go']['main']['App']['TriggerWind']();
}
