// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearThrowCoordinates() {
  return window['go']['main']['App']['ClearThrowCoordinates']();
}

export function ConnectNetworkDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectNetworkDevice'](arg1, arg2, arg3);
}

export function ConnectSerialDevice(arg1, arg2) {
  return window['go']['main']['App']['ConnectSerialDevice'](arg1, arg2);
}

export function DebugCalibrationData(arg1) {
  return window['go']['main']['App']['DebugCalibrationData'](arg1);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['App']['DisconnectDevice'](arg1);
}

export function EndThrowSession() {
  return window['go']['main']['App']['EndThrowSession']();
}

export function ExportHeatmapData(arg1, arg2) {
  return window['go']['main']['App']['ExportHeatmapData'](arg1, arg2);
}

export function ExportThrowCoordinates() {
  return window['go']['main']['App']['ExportThrowCoordinates']();
}

export function ExportThrowCoordinatesAsCSV() {
  return window['go']['main']['App']['ExportThrowCoordinatesAsCSV']();
}

export function ExportThrowCoordinatesForCircle(arg1) {
  return window['go']['main']['App']['ExportThrowCoordinatesForCircle'](arg1);
}

export function GetCalibration(arg1) {
  return window['go']['main']['App']['GetCalibration'](arg1);
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetReliableEDMReading(arg1) {
  return window['go']['main']['App']['GetReliableEDMReading'](arg1);
}

export function GetThrowStatistics(arg1) {
  return window['go']['main']['App']['GetThrowStatistics'](arg1);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function MeasureThrow(arg1) {
  return window['go']['main']['App']['MeasureThrow'](arg1);
}

export function MeasureWind(arg1) {
  return window['go']['main']['App']['MeasureWind'](arg1);
}

export function ResetCalibration(arg1) {
  return window['go']['main']['App']['ResetCalibration'](arg1);
}

export function SaveCalibration(arg1, arg2) {
  return window['go']['main']['App']['SaveCalibration'](arg1, arg2);
}

export function SendToScoreboard(arg1) {
  return window['go']['main']['App']['SendToScoreboard'](arg1);
}

export function SetCircleCentre(arg1) {
  return window['go']['main']['App']['SetCircleCentre'](arg1);
}

export function SetDemoMode(arg1) {
  return window['go']['main']['App']['SetDemoMode'](arg1);
}

export function StartThrowSession(arg1, arg2) {
  return window['go']['main']['App']['StartThrowSession'](arg1, arg2);
}

export function StartWindListener(arg1, arg2) {
  return window['go']['main']['App']['StartWindListener'](arg1, arg2);
}

export function VerifyCircleEdge(arg1) {
  return window['go']['main']['App']['VerifyCircleEdge'](arg1);
}
