// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName():Promise<string>;

export function GetMockEvents():Promise<Array<Record<string, any>>>;

export function SendToScoreboard(arg1:string):Promise<void>;

export function TriggerEDM():Promise<string>;

export function TriggerWind():Promise<string>;
